title: GitLab CI for Websites
email: alex@thorne.cc
description: >
  Boilerplate code for automatic build and deployment of websites on GitLab CI
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thornecc.github.com/gitlab-ci-website" # the base hostname & protocol for your site
github_username:  thornecc

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
